version: 2
jobs:
  test_jdk8_with_coverage:
    working_directory: ~/styx
    docker:
      - image: maven:3.5.2-jdk-8
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline compile
      - save_cache:
          key: v1-deps-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run: mvn verify
      - run: bash <(curl -s https://codecov.io/bash) -f '!**/jacoco-aggregate/**'
      - run: |
          mkdir test-reports
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} test-reports/ \;
      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: styx-report/target/site/jacoco-aggregate/
          destination: jacoco-aggregate

  test_jdk9:
    working_directory: ~/styx
    docker:
      - image: maven:3.5.2-jdk-9-slim
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-jdk9-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline compile
      - save_cache:
          key: v1-deps-jdk9-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run: mvn verify


workflows:
  version: 2
  build:
    jobs:
      - test_jdk8_with_coverage
      - test_jdk9
